"use client";
import React, { useState } from 'react'
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contact - Zee',
  description: 'Generated by NEXT',
}

const contact = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    address: '',
    textMessage: '',
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = () => {
    console.log(formData);
  };

  return (
    <main className='mh-according-height-header-footer'>
      <div className='container mx-auto'>
        <h1 className='text-7xl font-extrabold text-center mb-8 uppercase text-orange-600'>Contact Us</h1>
        <div className='grid grid-cols-2 gap-4'>
          <div>
            <input
              type="text"
              placeholder="Name"
              className="input input-bordered input-secondary w-full"
              name="name"
              value={formData.name}
              onChange={handleInputChange}
            />
          </div>
          <div>
            <input
              type="text"
              placeholder="Email"
              className="input input-bordered input-secondary w-full"
              name="email"
              value={formData.email}
              onChange={handleInputChange}
            />
          </div>
          <div className='col-span-2'>
            <input
              type="text"
              placeholder="Address"
              className="input input-bordered input-secondary w-full"
              name="address"
              value={formData.address}
              onChange={handleInputChange}
            />
          </div>
          <div className='col-span-2'>
            <textarea
              className="textarea textarea-secondary resize-none w-full h-36"
              placeholder="Message"
              name="textMessage"
              value={formData.textMessage}
              onChange={handleInputChange}
            ></textarea>
          </div>
          <div className='text-center col-span-2'>
            <button onClick={handleSubmit} className='btn btn-secondary w-full uppercase bg-orange-600'>Submit</button>
          </div>
        </div>
      </div>
    </main>
  )
}

export default contact
